# Generated by Django 2.1.7 on 2019-03-27 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_name',
            new_name='question_text',
        ),
    ]
